### ISSUE TITLE
Stop timer alarm without going to the next question

### ISSUE THREAD

**Issue by Chieze-Franklin** [andela-stuff/sims-games#7]
There should be a way to stop the timer alarm without going to the next question.

#### Dev Note

Add another state to that button. So when the button counts down to zero, this new state (end alarm) should become the state of the button. Clicking the button then ends the alarm and shows "NEXT".

**Comment by appcypher** [comment]
This has been fixed in the following PR:
https://github.com/andela-stuff/sims-games/pull/9

**Comment by Chieze-Franklin** [comment]
Reopening this because the alarm doesn't seem to stop as expected.

**Comment by Chieze-Franklin** [comment]
This has been resolved in [PR 14](https://github.com/andela-stuff/sims-games/pull/14)
