### ISSUE TITLE
Show question numbers

### ISSUE THREAD

**Issue by Chieze-Franklin** [andela-stuff/sims-games#8]
We need to show the question numbers. It is important as the leaderboard requires that the question number be recorded also be recorded.

#### Dev Note

This may require a change to the JSON structure of the incoming data.
So instead of having
```javascript
"tasks": [
    "Seek clarity on what you are expected to deliver for the MVP. GO FOR IT!"
]
```

We could have
```javascript
"tasks": [
    {
        "number": 1,
        "body": "Seek clarity on what you are expected to deliver for the MVP. GO FOR IT!"
    }
]
```

**Comment by appcypher** [comment]
This has been fixed in the following PR:
https://github.com/andela-stuff/sims-games/pull/9
